### ISSUE TITLE
Your package breaks when defunct future::multiprocess will be removed

### ISSUE THREAD

**Issue by HenrikBengtsson** [XikunHan/metabolomicsR#2]
FYI, `future::multiprocess` has been deprecated since October 2020, and defunct since March 2023.  It will soon be removed from **future**.  When that happens, your package will break (see below).  Could you please fix this?  It's probably not used by your package anyway, since it's already defunct.  Thank you.

*   checking dependencies in R code ... WARNING
    ```
    Missing or unexported object: ‘future::multiprocess’
    ```

**Comment by HenrikBengtsson** [comment]
A friendly reminder about this one

**Comment by HenrikBengtsson** [comment]
Friendly reminder: Your package will fail CRAN checks with the next release of the **future** package, because of this.

**Comment by XikunHan** [comment]
Thank you for the reminder. I have not conducted active testing of this package on CRAN. 
For the latest version, please install the package directly from GitHub using the following command: remotes::install_github("XikunHan/metabolomicsR")
